const int PLAY_FIELD_WIDTH  =  255;
const int PLAY_FIELD_HEIGHT =  350;

const int PLAY_FIELD_LEFT   = -PLAY_FIELD_WIDTH / 2;
const int PLAY_FIELD_RIGHT  =  PLAY_FIELD_WIDTH / 2;
const int PLAY_FIELD_TOP    =  PLAY_FIELD_HEIGHT / 2;
const int PLAY_FIELD_BOTTOM = -PLAY_FIELD_HEIGHT / 2;

